### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [minghanz/cvo_ops#1]
Hi, I'm very interested in applying this loss in some of my projects. Could you please provide an example script, showing how to prepare the information for the C3DLoss class (especially CamProj, without using DataReaderKITTI)? Also, what exactly are the masks we have to provide?

**Comment by minghanz** [comment]
Hi @VitorGuizilini-TRI , I just updated the readme and now there is a link to our DORN implementation using the C3D loss. I think you may find what you need there. Feel free to ask if there are further questions. Thanks!

**Comment by minghanz** [comment]
To be more specific: 

- The basic camera intrinsic and extrinsic information is stored in `InExtr` class in `utils_general/calib.py`. 
- `CamInfo` class in `utils/cam_proj.py` takes `InExtr` instance as input to generate unit-depth point clouds corresponding to the pixels. These point clouds are frequently used when 3D loss is used. The class also supports operations like cropping and scaling so that we can generate new `CamInfo` instances when image augmentation is used. 
- `CamProj` class hosts a set of `CamInfo` if all images in the dataset corresponds to a few camera intrinsic/extrinsic setups. In this case we preload the `CamInfo` instances and do not calculate them for every images. However this is optional. You can use  `CamInfo` only to hold the camera information. 
- `depth_gt_mask` is to indicate those pixels with valid depth values. It's simply where the depth image value is larger than zero, for example. `depth_mask` in my practice is generated by a dilation operation on the `depth_gt_mask` to get all pixels corresponding to regions roughly covered by the LIDAR, which are generally those pixels we care in depth prediction.
